version: '3.3'

services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.1
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./traefik.yaml
        target: /etc/traefik/traefik.yaml
      - type: bind
        source: ./acme.json
        target: /acme.json
      - type: bind
        source: ./logs/access.log
        target: /var/log/traefik/access.log
      - type: bind
        source: ./logs/traefik.log
        target: /var/log/traefik/traefik.log
    labels:
      - "traefik.http.routers.apiRedirect.rule=Host(`traefik.mahdi.cloud`)"
      - "traefik.http.routers.apiRedirect.entryPoints=web"
      - "traefik.http.routers.apiRedirect.middlewares=redirect@docker"
      - "traefik.http.routers.api.rule=Host(`traefik.mahdi.cloud`)"
      - "traefik.http.routers.api.entryPoints=websecure"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certResolver=le"
      - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$biwD3cDr$$4.qbOKzsc/ufaFO41GB.W/"
      - "traefik.http.middlewares.redirect.redirectScheme.scheme=https"

  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoamiRedirect.rule=Host(`whoami.traefik.mahdi.cloud`)"
      - "traefik.http.routers.whoamiRedirect.entryPoints=web"
      - "traefik.http.routers.whoamiRedirect.middlewares=redirect@docker"
      - "traefik.http.routers.whoami.rule=Host(`whoami.traefik.mahdi.cloud`)"
      - "traefik.http.routers.whoami.entryPoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certResolver=le"
