providers:
  docker: {}

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Those were not picked up by Traefik for an unknown reason
#http:
#  middlewares:
#    httpRedirect:
#      redirectScheme:
#        scheme: https
#  routers:
#    httpRedirectRouter:
#      rule: "Host(`*`)"
#      entrypoints:
#        - web
#      middlewares:
#        - httpRedirect@file

certificatesResolvers:
  le:
    acme:
      email: "mahdi@mahdialkhalaf.com"
      storage: acme.json
      # uncomment to use the staging server
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

metrics:
  prometheus: {}

tracing:
  jaeger: {}

accessLog:
  filePath: "/var/log/traefik/access.log"

log:
  filePath: "/var/log/traefik/traefik.log"
